[versions]
fawe = "2.15.3"
mongodb = "5.10.0"
mccoroutine = "2.22.0"
interfaces = "2.1.1-SNAPSHOT"
kotlinxSerialization = "1.11.0"
scoreboard = "2.8.2"
nuvotifier = "2.7.2"
jda = "6.4.2"
jdaKtx = "0.15.0"
kotlinxSerializationProperties = "1.9.0"
dotenvKotlin = "6.5.1"
lamp = "4.0.0-rc.18"
discordWebHooks = "0.8.4"

[libraries]
# Fawe
fawe-core = { module = "com.fastasyncworldedit:FastAsyncWorldEdit-Core", version.ref = "fawe" }
fawe-bukkit = { module = "com.fastasyncworldedit:FastAsyncWorldEdit-Bukkit", version.ref = "fawe" }

# MongoDB
mongodb = { module = "org.mongodb:mongodb-driver-kotlin-coroutine", version.ref = "mongodb" }

# Mccoroutine
mccoroutine-bukkit-api = { module = "com.github.shynixn.mccoroutine:mccoroutine-bukkit-api", version.ref = "mccoroutine" }
mccoroutine-bukkit-core = { module = "com.github.shynixn.mccoroutine:mccoroutine-bukkit-core", version.ref = "mccoroutine" }

mccoroutine-velocity-api = { module = "com.github.shynixn.mccoroutine:mccoroutine-velocity-api", version.ref = "mccoroutine" }
mccoroutine-velocity-core = { module = "com.github.shynixn.mccoroutine:mccoroutine-velocity-core", version.ref = "mccoroutine" }

# Noxcrew
interfaces = { module = "com.noxcrew.interfaces:interfaces", version.ref = "interfaces" }

kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }

# Megavex Scoreboard Library
scoreboard-library-api = { module = "net.megavex:scoreboard-library-api", version.ref = "scoreboard" }
scoreboard-library-implementation = { module = "net.megavex:scoreboard-library-implementation", version.ref = "scoreboard" }
scoreboard-library-extra-kotlin = { module = "net.megavex:scoreboard-library-extra-kotlin", version.ref = "scoreboard" }

# NuVotifier
nuvotifier-api = { module = "com.github.NuVotifier.NuVotifier:nuvotifier-api", version.ref = "nuvotifier" }
nuvotifier-velocity = { module = "com.github.NuVotifier.NuVotifier:nuvotifier-velocity", version.ref = "nuvotifier" }

# JDA
jda = { module = "net.dv8tion:JDA", version.ref = "jda" }
jda-ktx = { module = "club.minnced:jda-ktx", version.ref = "jdaKtx" }

kotlinx-serialization-properties = { module = "org.jetbrains.kotlinx:kotlinx-serialization-properties", version.ref = "kotlinxSerializationProperties" }
dotenv-kotlin = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenvKotlin" }

# Lamp
lamp-common = { module = "io.github.revxrsal:lamp.common", version.ref = "lamp" }
lamp-jda = { module = "io.github.revxrsal:lamp.jda", version.ref = "lamp" }

discord-webhooks = { module = "club.minnced:discord-webhooks", version.ref = "discordWebHooks" }

[bundles]
ggnext-core = [
    "mccoroutine-bukkit-api",
    "mccoroutine-bukkit-core",
    "mongodb",
    "interfaces",
    "kotlinx-serialization-json",
    "scoreboard-library-api",
    "scoreboard-library-extra-kotlin"
]

ggnext-velocity = [
    "mongodb",
    "mccoroutine-velocity-api",
    "mccoroutine-velocity-core",
    "discord-webhooks"
]

dc-bot = [
    "jda",
    "jda-ktx",
    "kotlinx-serialization-properties",
    "dotenv-kotlin",
    "mongodb",
    "lamp-common",
    "lamp-jda"
]

ggnext-common = [
    "kotlinx-serialization-json"
]